In [51]:
import pandas as pd
import numpy as np
from collections import defaultdict

In [41]:
seds = pd.read_csv('datasets/seds.csv')

In [50]:
seds.head()

year    msn state_name state_code  \
0  1960  ABICB     Alaska         AK   
1  1961  ABICB     Alaska         AK   
2  1962  ABICB     Alaska         AK   
3  1963  ABICB     Alaska         AK   
4  1964  ABICB     Alaska         AK   

                                         description energy_bin  value  \
0  Aviation gasoline blending components consumed...  Petroleum    0.0   
1  Aviation gasoline blending components consumed...  Petroleum    0.0   
2  Aviation gasoline blending components consumed...  Petroleum    0.0   
3  Aviation gasoline blending components consumed...  Petroleum    0.0   
4  Aviation gasoline blending components consumed...  Petroleum    0.0   

          unit  
0  Billion Btu  
1  Billion Btu  
2  Billion Btu  
3  Billion Btu  
4  Billion Btu

In [52]:
msn_map = defaultdict(list)

In [53]:
count = 0
for i in seds.values:
    msn_map[i[1]].append(i)

In [56]:
msn_map["ABICB"]

[array([1960, 'ABICB', 'Alaska', 'AK',
        'Aviation gasoline blending components consumed by the industrial sector',
        'Petroleum', 0.0, 'Billion Btu'], dtype=object),
 array([1961, 'ABICB', 'Alaska', 'AK',
        'Aviation gasoline blending components consumed by the industrial sector',
        'Petroleum', 0.0, 'Billion Btu'], dtype=object),
 array([1962, 'ABICB', 'Alaska', 'AK',
        'Aviation gasoline blending components consumed by the industrial sector',
        'Petroleum', 0.0, 'Billion Btu'], dtype=object),
 array([1963, 'ABICB', 'Alaska', 'AK',
        'Aviation gasoline blending components consumed by the industrial sector',
        'Petroleum', 0.0, 'Billion Btu'], dtype=object),
 array([1964, 'ABICB', 'Alaska', 'AK',
        'Aviation gasoline blending components consumed by the industrial sector',
        'Petroleum', 0.0, 'Billion Btu'], dtype=object),
 array([1965, 'ABICB', 'Alaska', 'AK',
        'Aviation gasoline blending components consumed by the ind

In [26]:
seds.filter(regex="....S", axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1711736 rows x 0 columns]

In [21]:
for item in arr:
    if item[4] == "S":
        print(item)

TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGDS
TEGD